//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityForCard
    {
        public int ID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> ActivityID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Card_ Card_ { get; set; }
    }
}
