//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public string Full_Name { get; set; }
        public int CardID { get; set; }
        public Nullable<int> Number_of_activities { get; set; }
        public string Attendance_mode { get; set; }
        public Nullable<decimal> Total_cost { get; set; }
    }
}
